export const GET_MOVIES = "GET_MOVIES";
export const IS_LOADING = "IS_LOADING";
export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const TOGGLE_LIKE_MOVIE = "TOGGLE_LIKE_MOVIE";
export const TOGGLE_DISLIKE_MOVIE = "TOGGLE_DISLIKE_MOVIE";
export const PAGINATE_MOVIES = "PAGINATE_MOVIES";

//Categories Actions

export const SELECT_CATEGORY = "SELECT_CATEGORY";
